sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '4.3'
notifications:
  slack:
    secure: QB0+Dmb0tPVVNqP7FVBhdcWRe3sOkpOLRDYcSAyWL/RNYKAt3TkwgQYfIcHcq5OpFaWzymhMuSQ7xhHVCODiYZ1P5T5sDEDVi4FFjoVq+iBQVzk9O0Q0xUalkfsBMw+eA2TJKrzJrVLHHWnHnDLo7CQd3SCG2z1ApvYl5jumkjaVsSWhz93XRZqZhFAjtmQTkEYLZtIX/GCsH7XdihUKS/WxUJagx+I/wqYoafbiuZsnFQepOgwUFxlIz/Prqr75wasiPJVywqbvWOJQyhAKrSkM4/FwewZD/iQmc1WKqX7Alavka9KYO0sY711rRjJVmQKy2fDN/pyy8VMek2gMm5fXyczRtC8ZONvLBlm4u4dWahtuxkpQT0D/c+zju4L6DsCT7QriXxYfoDhBxC8OG/+tWvhAE2dnVFBo6kid11WPP/+uYVnzZxq2ft6ridnMu0pp8TuEtcLb4CopOJ4jxXwTel/OauR0ly8HC2QYy53jL7eHdXHJtZNTYdafy8EzAxQoLP2RslRt0dyUAqtowx6oYMMp4bXB/vbPNkd1QB1O+TVgTzjCTqtbYwNzl8qtnDMrxZwrFzLxwM1pcpDLE0gUFmgaAOqaoOGECsbL1HnVmXs2r2VrBf2cVJuRWCLE/dE8pHrUWDvRporGOcOOxNzY6d3KB/YWAVsULeMwp8c=
env:
  global:
  - STAGE: dev
  - GECKOBOARD_WIDGET_KEY: 32629-cb51fde0-41ef-0134-97f3-22000bdb45ae
  - secure: JPUxV6iJPJwfhMeKzEghhIvZ6b5HAgDFlL+ackXwxQM72h01bsYyklHlZfJixlDxcor9kOvonw6JTu7rLnhf5fXB+k9kZF8gLY+2wRWE2/e6LR/B6wlSJfTGvNZeBFRs4pERc7XA4CcBN/18EWIkYMZemdEgdNzf0Ys8OAha9rmHZJOoHQrdFg4FdVVdeqIdMtA96qeW0Q22DEKuDt7tzRGGGbNYz5L+cxp8+t2IMwZ1McBjA1aHVbL5PU4o9CBiOyofwr1kxYg+3OtI6JkLr3kaR4PvnLbyGESSspFewa/AXc7ZjY4D6erqtFkfKZSR34YxE/1LzXTRQ8bXZVUKi3vC8sPnojj09OeG3fndOrFmEmFRT7ysNgQpCifp9H34L+ZZam9GwTuYZQ74bMEan8XYwdqLKgW4U3CrpUGTNeqafsnkDZpbP4ivPu6qP+OcNdQpJcnk9QqxPHkXHJZ4h3YyW0sgLpKYJPCbsrQ3UiFqkS2/xVQDexn+bG/b84iJBeGijaIYArVEZDBXkZ7GD4gpDwZBSM563MW+QzVmj6inWECE+luj/aVYj9RSw0zc+JRaWOutH6Q48Tvc8FpZp47xZLfl0R85L6BPInc46hX7PLxjjv/TGvvjn5d6ahknCsB1NPc/KLd8LRpCF+bPGtRm8j5dGIf2gQHzNLyYCx4=
before_install:
- npm install -g npm@3
- npm install @mallzee/travis-notify-geckoboard
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run geckoboard-start; fi
before_script:
- npm prune
script:
- npm test
- STAGE=$([ "$TRAVIS_BRANCH" == "master"] && echo "prod" || echo "dev")
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run semantic-release; npm run deploy $STAGE; fi
after_script:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run geckoboard; fi
branches:
  except:
  - /^v\d+\.\d+\.\d+$/

