# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: serverless-boilerplate
provider: aws
runtime: nodejs4.3

# you can overwrite defaults here
defaults:
    stage: dev
    region: eu-west-1

# you can add packaging information here
#package:
#    include:
#        - include-me.js
#    exclude:
#        - exclude-me.js
#    artifact: my-service-code.zip

functions:

    hello:
        handler: handler.hello
        events:
          - http:
              path: greet
              method: get

#           - s3: ${bucket}
#           - schedule: rate(10 minutes)
#           - sns: greeter-topic

# you can add CloudFormation resource templates here
resources:
    Resources:
        DynamoDBBoilerplateTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${stage}-serverless-boilerplate
                AttributeDefinitions:
                    -
                        AttributeName: message
                        AttributeType: S
                KeySchema:
                    -
                        AttributeName: message
                        KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 5
                    WriteCapacityUnits: 5
        IamPolicyDynamoDB:
            Type: AWS::IAM::Policy
            DependsOn: DynamoDBBoilerplateTable
            Properties:
                PolicyName: ${stage}-${service}-lambda-dynamodb
                PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      -
                          Effect: Allow
                          Action:
                            - dynamodb:GetItem
                            - dynamodb:PutItem
                          Resource: "arn:aws:dynamodb:*:*:table/${stage}-serverless-boilerplate"
                Roles:
                  -
                      Ref: IamRoleLambda
