vars: null
stages:
    dev:
        vars:
            stage: dev
            service: overlord
        regions:
            eu-west-1:
                vars:
                    iamRoleArnLambda: >-
                        arn:aws:iam::086317975330:role/serverless-boilerplate-dev-IamRoleLambda-FCDHJNGM46MM
                    serverlessDeploymentBucketName: >-
                        serverless-boilerplate-d-serverlessdeploymentbuck-mff0p797q8nj
